FROM node:8-alpine
Run mkdir -p C:\Users\CHIRANJEEVI MANCHALA\Devops1\New-ECS-Project\app
WORKDIR C:\Users\CHIRANJEEVI MANCHALA\Devops1\New-ECS-Project\app
COPY . .
RUN npm install
EXPOSE 3000
CMD [ "node", "new.js" ]
